language: ruby
rvm:
  - 2.1.5
sudo: false
before_script: 
  - mysql -e 'create database camilo_test;'
  - "sh -e /etc/init.d/xvfb start"
script: PADRINO_ENV=ci padrino rake
bundler_args: --without development production